### ISSUE TITLE
Does it support the Stream class?

### ISSUE THREAD

**Issue by Mark-81** [stm32duino/STM32Ethernet#13]
Just to be sure, because I cannot understand this from the documentation. Does the STM32Ethernet library support the Arduino [Stream](https://www.arduino.cc/reference/en/language/functions/communication/stream/) class?

**Comment by fpistm** [comment]
Hi @Mark-81 
Yes, this is the same API than Arduino.
EthernetClient inherits from Client Class which inherits from Stream
EthernetServer inherits from Server Class which inherits from Stream

**Comment by fpistm** [comment]
Hi @Mark-81 
is it ok to close this issue ?
