### ISSUE TITLE
Support for DP83848_PHY ?

### ISSUE THREAD

**Issue by stevstrong** [stm32duino/STM32Ethernet#15]
Hi,
tried to use this lib on a Arch Max board which is equipped with **DP83848J** chip, but compile fails for `ethernetif.c` on accessing the registers `PHY_IMR` and `PHY_ISFR,` which are obviously only defined for **LAN8742A_PHY** by this lib.

Searching the Arduino_Core_STM32 files, I could find in several headers `DP83848_PHY_ADDRESS` and some of its registers. However, `PHY_IMR` is not defined there. What is then the reason to define this phy in the core? The STM32Ethernet lib does not seem to support this PHY. How can this PHY be used with Arduino_Core_STM32 core?

Is there any plan for this lib to support the `DP83848` PHY?

**Comment by fpistm** [comment]
Hi @stevstrong 
`DP83848_PHY_ADDRESS`  is in fact by default in the `stm32f4xx_hal_conf.h` because this is the default in the `stm32f4xx_hal_conf_template.h`.
Yes, I never test with this as I do not test a board with this.
This could be fine to do that.

**Comment by fpistm** [comment]
Track in #34
