### ISSUE TITLE
Ethernet.linkStatus()

### ISSUE THREAD

**Issue by sstaub** [stm32duino/STM32Ethernet#19]
Can you add an Ethernet.linkStatus() function? This will helpful handling connection timeouts.
The function is described at https://www.arduino.cc/en/Reference/EthernetLinkStatus

**Comment by fpistm** [comment]
I will have to check if possible.

**Comment by sstaub** [comment]
There is a similar functionality in mbed, get_connection_status(), maybe that helps
https://os.mbed.com/docs/mbed-os/v5.11/mbed-os-api-doxy/class_network_interface.html#ad7d73134d58bfb2a0eabb5228b1332eb
