### ISSUE TITLE
macAddress function name

### ISSUE THREAD

**Issue by ramboerik** [stm32duino/STM32Ethernet#35]
Hi, I'm using the library and noticed that the name  of the function `macAddress` differs from arduino's own library. 

```
Arduino Ethernet: MACAddress
STM32Ethernet: macAddress
```
This is a bit frustrating as I'm compiling for multiple library implementations and is forced to write a wrapper around the function to unify the name. Could the function name  be changed to `MACAddress` alternative add a wrapper to make it interchangeable with [Arduino's library](https://www.arduino.cc/en/Reference/EthernetMACAddress)?

**Comment by fpistm** [comment]
Hi @ramboerik 
Thanks for this issue.
I will rename it and does not kept backward compatibility for this to ensure user use the correct name.

**Comment by ramboerik** [comment]
Thanks 👍!
