### ISSUE TITLE
STM32F103C compile problem

### ISSUE THREAD

**Issue by chenjeff622** [stm32duino/STM32Ethernet#39]
Arduino Core for STM32 1.8.0
generic STM32F103C blue pill
W5500 soc

#include <STM32Ethernet.h> <--- error log here
\libraries\STM32duino_STM32Ethernet\src/utility/stm32_eth.h:42:23: fatal error: stm32_def.h: No such file or directory

**Comment by fpistm** [comment]
This library does not support W5500 soc.
This is for STM32 series with Ethernet capabilities., STM32F103C does not have this support.
