### ISSUE TITLE
Hardware Timer

### ISSUE THREAD

**Issue by ats3788** [stm32duino/STM32Ethernet#47]
Hello 
I fiddle with the STM32F1 Blue Pill Board and got the Problem with Hardware Timer

src\main.cpp:137:37: error: no matching function for call to 'HardwareTimer::attachInterrupt(void (*)())'

void  __Timer1()
{
}
void SetupTimer()
{
 Timer1.setPeriod(1000000); // in microseconds = 1 second
    Timer1.attachInterrupt(&__Timer1);
    Timer1.resume();
}
I read that something changed in Core 1.9

**Comment by fpistm** [comment]
Yes API has changed with 1.9.0.
See https://github.com/stm32duino/Arduino_Core_STM32/pull/892

Why open an issue here? This is not related to STM32 Ethernet.
For this kind of issue or support, please use the forum: https://www.stm32duino.com
