### ISSUE TITLE
stm32_eth.c unknown type name 'stimer_t'

### ISSUE THREAD

**Issue by gurulator** [stm32duino/STM32Ethernet#6]
I am trying to compile ethernet examples for F746-discovery, but there is always the same error shown the picture (Documents\Arduino\libraries\STM32Ethernet-master\src\utility\stm32_eth.c:100:8: error: unknown type name 'stimer_t'). I already installed LwIP-master. I have no idea what's wrong.
![ethernet_error](https://user-images.githubusercontent.com/33238235/32200451-f4e0a912-bdd1-11e7-9019-9064f8445b29.PNG)

**Comment by fpistm** [comment]
Hi @gurulator ,
Which core you used?

**Comment by gurulator** [comment]
ARM® Cortex®-M7 core-based STM32F746NGH6 microcontroller, and the STM32GENERIC  implementation. https://github.com/ChrisMicro/STM32GENERIC
All the example codes are working well incuded in STM32GENERIC except the ethernet examples.
I am able to use the I/O pins and the TFT capacitive screen, but when I include the <STM32Ethernet.h>, the comiler displays the error report shown above.
http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-discovery-kits/32f746gdiscovery.html

**Comment by fpistm** [comment]
Ok that's why I thought. The latest version of this library is not compatible with STM32generic core.
This library is mainly for the https://github.com/stm32duino/Arduino_Core_STM32
Library now use a timer to call periodically the lwip scheduler.
Ask to @danieleff if he wants add wrapper to timer use in his core, here:
https://github.com/danieleff/STM32GENERIC/tree/master/STM32/libraries/OfficialCompatibility

**Comment by gurulator** [comment]
Ok, thanks for help.

**Comment by gurulator** [comment]
Now i tried it with the First release and it works fine, that was the problem.
https://github.com/stm32duino/STM32Ethernet/releases/tag/1.0.0
Thanks one more time!

**Comment by fpistm** [comment]
No worries ;)
It should be fine to unified API.
It's planned to extend timer API for https://github.com/stm32duino/Arduino_Core_STM32
We will try to do it as generic as possible.
