### ISSUE TITLE
I want Ethernet to work using the Generic F405/F407 variant

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/STM32Ethernet#70]
I am using BLACK F407VE board and LAN8742A_PHY.

The core version is 2.2.

I specify ```BLACK F407VE``` for Board part number.

![STM32-Ethernet-1](https://user-images.githubusercontent.com/6020549/231928572-ceda8e46-0cec-45f0-96f7-b6ec7ff62bd3.jpg)

Also add this definition:

Ethernet works.

```
#define HAL_ETH_MODULE_ENABLED
```

F405 and F407 support Ethernet.

If I change the Board part number to ```Generic F407VETx```, Ethernet doesn't work.

![STM32-Ethernet-2](https://user-images.githubusercontent.com/6020549/231928523-1fce2fe8-ab7d-4db0-9b89-e9c5aee942b7.jpg)

Do you have any plans to use the Generic F405/F407 variant to make Ethernet work?

**Comment by fpistm** [comment]
There is no plan, ti is just that generic could requires some configuration to be inline with your hardware,  like update the `SystemClock_Config` and configure the `HSE `as generic only used by default internal clock. Pay attention to define the correct HSE value as by default for F4 it is `8000000U `but some can have different one.
You can also redefine the `PinMap_Ethernet `array to configure the required set of pins....
