### ISSUE TITLE
addition of support for the NUCLEO-H743ZI2 to your library.

### ISSUE THREAD

**Issue by DrRaphael** [stm32duino/STM32Ethernet#79]
Dear author of the open source library,

I am writing to request the addition of support for the NUCLEO-H743ZI2 to your library. As a user of your library, I have found it to be an invaluable resource for my project. However, I am currently facing a challenge with regards to the NUCLEO-H743ZI2 board not being fully supported by your library.
I recognize that adding support for a new board requires significant effort and expertise. Therefore, I am willing to assist in any way possible to contribute to the development of this new feature. I have some experience with embedded systems programming and would be happy to assist with testing, bug reporting, or even contributing code if needed.
Thank you for considering my request. I look forward to hearing from you soon.
Best regards,
Raphael
[ Due to my poor English, this letter was generated by AIGC. Please understand ]

**Comment by fpistm** [comment]
Hi @DrRaphael 
Thanks for the interest, the main work to achieve is #34.
I hope have time for this but can't tell when.
I close this one as linked to #34.
