### ISSUE TITLE
Ethernet.MACAddress should be a getter, not setter

### ISSUE THREAD

**Issue by JAndrassy** [stm32duino/STM32Ethernet#81]
Ethernet.MACAddress should be a getter, not setter

https://github.com/arduino-libraries/Ethernet/blob/39103da0e1bc569023625ee4693272773397dbb6/src/Ethernet.cpp#L147-L153
```
void EthernetClass::MACAddress(uint8_t *mac_address)
{
	SPI.beginTransaction(SPI_ETHERNET_SETTINGS);
	W5100.getMACAddress(mac_address);
	SPI.endTransaction();
}
```

**Comment by sstaub** [comment]
I'm confused, what is the problem for this library? You mention the Arduino Ethernet library which uses the WIZnet chips.

**Comment by JAndrassy** [comment]
in this library it is a setter. that is wrong

**Comment by sstaub** [comment]
Have a look to the documentation. The implementation is different to the original Arduino library.

**Comment by fpistm** [comment]
Agreed with @sstaub . Getter is available with different prototype which is more clear: 
https://github.com/stm32duino/STM32Ethernet/blob/cd50f45d53fefd1b947b2a2552f672f328321a3f/src/STM32Ethernet.cpp#L136C1-L136C1
