### ISSUE TITLE
Compiling Issue!

### ISSUE THREAD

**Issue by Katheesh** [stm32duino/STM32Ethernet#91]
Check and solve the logs

Compiling .pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/EthernetClient.cpp.o
Compiling .pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/EthernetServer.cpp.o
Compiling .pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/EthernetUdp.cpp.o
Compiling .pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/STM32Ethernet.cpp.o
Compiling .pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/utility/ethernetif.cpp.o
Compiling .pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/utility/stm32_eth.cpp.o
lib/STM32Ethernet-1.4.0/src/utility/stm32_eth.cpp:67:4: warning: #warning "Default timer used to call ethernet scheduler at regular interval: TIM14" [-Wcpp]
   67 |   #warning "Default timer used to call ethernet scheduler at regular interval: TIM14"
      |    ^~~~~~~
Compiling .pio/build/genericSTM32F407VET6/src/main.cpp.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp: In function 'void low_level_init(netif*)':
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:170:18: error: 'struct ETH_InitTypeDef' has no member named 'AutoNegotiation'
  170 |   EthHandle.Init.AutoNegotiation = ETH_AUTONEGOTIATION_ENABLE;
      |                  ^~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:171:18: error: 'struct ETH_InitTypeDef' has no member named 'Speed'
  171 |   EthHandle.Init.Speed = ETH_SPEED_100M;
      |                  ^~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:172:18: error: 'struct ETH_InitTypeDef' has no member named 'DuplexMode'
  172 |   EthHandle.Init.DuplexMode = ETH_MODE_FULLDUPLEX;
      |                  ^~~~~~~~~~
Compiling .pio/build/genericSTM32F407VET6/lib63b/ModbusMaster/ModbusMaster.cpp.o
In file included from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/STM32F4xx/stm32f4xx_hal_conf.h:13,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:29,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:287,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/stm32_def.h:36,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/clock.h:19,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_time.h:23,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring.h:38,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/cores/arduino/Arduino.h:36,
                 from src/main.cpp:1:
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/STM32F4xx/stm32f4xx_hal_conf_default.h:315: warning: "LAN8742A_PHY_ADDRESS" redefined
  315 | #define LAN8742A_PHY_ADDRESS            0x00U
      | 
In file included from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/STM32F4xx/stm32f4xx_hal_conf.h:11:
src/hal_conf_extra.h:2: note: this is the location of the previous definition
    2 | #define LAN8742A_PHY_ADDRESS 0x01U
      | 
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:172:31: error: 'ETH_MODE_FULLDUPLEX' was not declared in this scope
  172 |   EthHandle.Init.DuplexMode = ETH_MODE_FULLDUPLEX;
      |                               ^~~~~~~~~~~~~~~~~~~
In file included from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:132,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/stm32_def.h:36,
                 from lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:48:
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h:11633:53: error: invalid conversion from 'long unsigned int' to 'ETH_MediaInterfaceTypeDef' [-fpermissive]
11633 | #define SYSCFG_PMC_MII_RMII_SEL_Msk          (0x1UL << SYSCFG_PMC_MII_RMII_SEL_Pos) /*!< 0x00800000 */
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h:11634:46: note: in expansion of macro 'SYSCFG_PMC_MII_RMII_SEL_Msk'
11634 | #define SYSCFG_PMC_MII_RMII_SEL              SYSCFG_PMC_MII_RMII_SEL_Msk       /*!<Ethernet PHY interface selection */
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h:1346:40: note: in expansion of macro 'SYSCFG_PMC_MII_RMII_SEL'
 1346 | #define ETH_MEDIA_INTERFACE_RMII      (SYSCFG_PMC_MII_RMII_SEL)
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:174:35: note: in expansion of macro 'ETH_MEDIA_INTERFACE_RMII'
  174 |   EthHandle.Init.MediaInterface = ETH_MEDIA_INTERFACE_RMII;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:181:18: error: 'struct ETH_InitTypeDef' has no member named 'RxMode'
  181 |   EthHandle.Init.RxMode = ETH_RXPOLLING_MODE;
      |                  ^~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:183:18: error: 'struct ETH_InitTypeDef' has no member named 'ChecksumMode'
  183 |   EthHandle.Init.ChecksumMode = ETH_CHECKSUM_BY_HARDWARE;
      |                  ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:184:18: error: 'struct ETH_InitTypeDef' has no member named 'PhyAddress'
  184 |   EthHandle.Init.PhyAddress = LAN8742A_PHY_ADDRESS;
      |                  ^~~~~~~~~~
Compiling .pio/build/genericSTM32F407VET6/libd83/STM32duino RTC/STM32RTC.cpp.o
Compiling .pio/build/genericSTM32F407VET6/libd83/STM32duino RTC/rtc.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:193:3: error: 'HAL_ETH_DMATxDescListInit' was not declared in this scope
  193 |   HAL_ETH_DMATxDescListInit(&EthHandle, DMATxDscrTab, &Tx_Buff[0][0], ETH_TXBUFNB);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/api_lib.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:196:3: error: 'HAL_ETH_DMARxDescListInit' was not declared in this scope
  196 |   HAL_ETH_DMARxDescListInit(&EthHandle, DMARxDscrTab, &Rx_Buff[0][0], ETH_RXBUFNB);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:223:48: error: invalid conversion from 'uint32_t*' {aka 'long unsigned int*'} to 'uint32_t' {aka 'long unsigned int'} [-fpermissive]
  223 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_IMR, &regvalue);
      |                                                ^~~~~~~~~
      |                                                |
      |                                                uint32_t* {aka long unsigned int*}
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:223:26: error: too few arguments to function 'HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef*, uint32_t, uint32_t, uint32_t*)'
  223 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_IMR, &regvalue);
      |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/STM32F4xx/stm32f4xx_hal_conf_default.h:424,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/STM32F4xx/stm32f4xx_hal_conf.h:13,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:29,
                 from /Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:287:
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h:2068:19: note: declared here
 2068 | HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef *heth, uint32_t PHYAddr, uint32_t PHYReg,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:228:27: error: too few arguments to function 'HAL_StatusTypeDef HAL_ETH_WritePHYRegister(const ETH_HandleTypeDef*, uint32_t, uint32_t, uint32_t)'
  228 |   HAL_ETH_WritePHYRegister(&EthHandle, PHY_IMR, regvalue);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h:2066:19: note: declared here
 2066 | HAL_StatusTypeDef HAL_ETH_WritePHYRegister(const ETH_HandleTypeDef *heth, uint32_t PHYAddr, uint32_t PHYReg,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp: In function 'err_t low_level_output(netif*, pbuf*)':
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:254:43: error: 'struct ETH_HandleTypeDef' has no member named 'TxDesc'; did you mean 'TxDescList'?
  254 |   uint8_t *buffer = (uint8_t *)(EthHandle.TxDesc->Buffer1Addr);
      |                                           ^~~~~~
      |                                           TxDescList
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:263:25: error: 'struct ETH_HandleTypeDef' has no member named 'TxDesc'; did you mean 'TxDescList'?
  263 |   DmaTxDesc = EthHandle.TxDesc;
      |                         ^~~~~~
      |                         TxDescList
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:269:21: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Status'
  269 |     if ((DmaTxDesc->Status & ETH_DMATXDESC_OWN) != (uint32_t)RESET) {
      |                     ^~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:284:53: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Buffer2NextDescAddr'
  284 |       DmaTxDesc = (ETH_DMADescTypeDef *)(DmaTxDesc->Buffer2NextDescAddr);
      |                                                     ^~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:287:23: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Status'
  287 |       if ((DmaTxDesc->Status & ETH_DMATXDESC_OWN) != (uint32_t)RESET) {
      |                       ^~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:292:39: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Buffer1Addr'
  292 |       buffer = (uint8_t *)(DmaTxDesc->Buffer1Addr);
      |                                       ^~~~~~~~~~~
.pio/libdeps/genericSTM32F407VET6/STM32duino RTC/src/STM32RTC.cpp:160:2: warning: #warning "only BCD mode is supported" [-Wcpp]
  160 | #warning "only BCD mode is supported"
      |  ^~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:307:3: error: 'HAL_ETH_TransmitFrame' was not declared in this scope; did you mean 'HAL_ETH_Transmit_IT'?
  307 |   HAL_ETH_TransmitFrame(&EthHandle, framelength);
      |   ^~~~~~~~~~~~~~~~~~~~~
      |   HAL_ETH_Transmit_IT
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/api_msg.c.o
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/err.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp: In function 'pbuf* low_level_input(netif*)':
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:346:7: error: 'HAL_ETH_GetReceivedFrame_IT' was not declared in this scope
  346 |   if (HAL_ETH_GetReceivedFrame_IT(&EthHandle) != HAL_OK) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:351:19: error: 'struct ETH_HandleTypeDef' has no member named 'RxFrameInfos'
  351 |   len = EthHandle.RxFrameInfos.length;
      |                   ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:352:33: error: 'struct ETH_HandleTypeDef' has no member named 'RxFrameInfos'
  352 |   buffer = (uint8_t *)EthHandle.RxFrameInfos.buffer;
      |                                 ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:360:27: error: 'struct ETH_HandleTypeDef' has no member named 'RxFrameInfos'
  360 |     dmarxdesc = EthHandle.RxFrameInfos.FSRxDesc;
      |                           ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:373:55: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Buffer2NextDescAddr'
  373 |         dmarxdesc = (ETH_DMADescTypeDef *)(dmarxdesc->Buffer2NextDescAddr);
      |                                                       ^~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:374:41: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Buffer1Addr'
  374 |         buffer = (uint8_t *)(dmarxdesc->Buffer1Addr);
      |                                         ^~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:389:25: error: 'struct ETH_HandleTypeDef' has no member named 'RxFrameInfos'
  389 |   dmarxdesc = EthHandle.RxFrameInfos.FSRxDesc;
      |                         ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:391:29: error: 'struct ETH_HandleTypeDef' has no member named 'RxFrameInfos'
  391 |   for (i = 0; i < EthHandle.RxFrameInfos.SegCount; i++) {
      |                             ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:392:16: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Status'
  392 |     dmarxdesc->Status |= ETH_DMARXDESC_OWN;
      |                ^~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:393:51: error: 'volatile struct ETH_DMADescTypeDef' has no member named 'Buffer2NextDescAddr'
  393 |     dmarxdesc = (ETH_DMADescTypeDef *)(dmarxdesc->Buffer2NextDescAddr);
      |                                                   ^~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:397:13: error: 'struct ETH_HandleTypeDef' has no member named 'RxFrameInfos'
  397 |   EthHandle.RxFrameInfos.SegCount = 0;
      |             ^~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp: In function 'uint8_t ethernetif_is_init()':
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:449:21: error: 'struct ETH_HandleTypeDef' has no member named 'State'; did you mean 'gState'?
  449 |   return (EthHandle.State != HAL_ETH_STATE_RESET);
      |                     ^~~~~
      |                     gState
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp: In function 'void ethernetif_set_link(netif*)':
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:509:49: error: invalid conversion from 'uint32_t*' {aka 'long unsigned int*'} to 'uint32_t' {aka 'long unsigned int'} [-fpermissive]
  509 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_ISFR, &regvalue);
      |                                                 ^~~~~~~~~
      |                                                 |
      |                                                 uint32_t* {aka long unsigned int*}
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:509:26: error: too few arguments to function 'HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef*, uint32_t, uint32_t, uint32_t*)'
  509 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_ISFR, &regvalue);
      |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h:2068:19: note: declared here
 2068 | HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef *heth, uint32_t PHYAddr, uint32_t PHYReg,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:516:48: error: invalid conversion from 'uint32_t*' {aka 'long unsigned int*'} to 'uint32_t' {aka 'long unsigned int'} [-fpermissive]
  516 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_BSR, &regvalue);
      |                                                ^~~~~~~~~
      |                                                |
      |                                                uint32_t* {aka long unsigned int*}
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:516:26: error: too few arguments to function 'HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef*, uint32_t, uint32_t, uint32_t*)'
  516 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_BSR, &regvalue);
      |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h:2068:19: note: declared here
 2068 | HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef *heth, uint32_t PHYAddr, uint32_t PHYReg,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp: In function 'void ethernetif_update_config(netif*)':
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:542:24: error: 'struct ETH_InitTypeDef' has no member named 'AutoNegotiation'
  542 |     if (EthHandle.Init.AutoNegotiation != ETH_AUTONEGOTIATION_DISABLE) {
      |                        ^~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:545:51: error: invalid conversion from 'uint32_t*' {aka 'long unsigned int*'} to 'uint32_t' {aka 'long unsigned int'} [-fpermissive]
  545 |       HAL_ETH_ReadPHYRegister(&EthHandle, PHY_SR, &regvalue);
      |                                                   ^~~~~~~~~
      |                                                   |
      |                                                   uint32_t* {aka long unsigned int*}
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:545:30: error: too few arguments to function 'HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef*, uint32_t, uint32_t, uint32_t*)'
  545 |       HAL_ETH_ReadPHYRegister(&EthHandle, PHY_SR, &regvalue);
      |       ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/KATHEESKUMAR/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h:2068:19: note: declared here
 2068 | HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef *heth, uint32_t PHYAddr, uint32_t PHYReg,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:553:24: error: 'struct ETH_InitTypeDef' has no member named 'DuplexMode'
  553 |         EthHandle.Init.DuplexMode = ETH_MODE_FULLDUPLEX;
      |                        ^~~~~~~~~~
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/if_api.c.o
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/netbuf.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:553:37: error: 'ETH_MODE_FULLDUPLEX' was not declared in this scope
  553 |         EthHandle.Init.DuplexMode = ETH_MODE_FULLDUPLEX;
      |                                     ^~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:556:24: error: 'struct ETH_InitTypeDef' has no member named 'DuplexMode'
  556 |         EthHandle.Init.DuplexMode = ETH_MODE_HALFDUPLEX;
      |                        ^~~~~~~~~~
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/netdb.c.o
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/netifapi.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:556:37: error: 'ETH_MODE_HALFDUPLEX' was not declared in this scope
  556 |         EthHandle.Init.DuplexMode = ETH_MODE_HALFDUPLEX;
      |                                     ^~~~~~~~~~~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:561:24: error: 'struct ETH_InitTypeDef' has no member named 'Speed'
  561 |         EthHandle.Init.Speed = ETH_SPEED_10M;
      |                        ^~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:564:24: error: 'struct ETH_InitTypeDef' has no member named 'Speed'
  564 |         EthHandle.Init.Speed = ETH_SPEED_100M;
      |                        ^~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:573:80: error: 'struct ETH_InitTypeDef' has no member named 'DuplexMode'
  573 |       HAL_ETH_WritePHYRegister(&EthHandle, PHY_BCR, ((uint16_t)(EthHandle.Init.DuplexMode >> 3) |
      |                                                                                ^~~~~~~~~~
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:574:80: error: 'struct ETH_InitTypeDef' has no member named 'Speed'
  574 |                                                      (uint16_t)(EthHandle.Init.Speed >> 1)));
      |                                                                                ^~~~~
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/sockets.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:578:36: error: 'ETH_MACInitTypeDef' was not declared in this scope; did you mean 'ETH_InitTypeDef'?
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |                                    ^~~~~~~~~~~~~~~~~~
      |                                    ETH_InitTypeDef
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:578:56: error: expected primary-expression before ')' token
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |                                                        ^
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/api/tcpip.c.o
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/core/altcp.c.o
lib/STM32Ethernet-1.4.0/src/utility/ethernetif.cpp:578:5: error: 'HAL_ETH_ConfigMAC' was not declared in this scope
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |     ^~~~~~~~~~~~~~~~~
Compiling .pio/build/genericSTM32F407VET6/libefe/LwIP-2.1.3/core/altcp_alloc.c.o
*** [.pio/build/genericSTM32F407VET6/libc3f/STM32Ethernet-1.4.0/utility/ethernetif.cpp.o] Error 1
=================================================================== [FAILED] Took 4.42 seconds ===================================================================

 *  The terminal process "platformio 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by fpistm** [comment]
Hi @Katheesh
PIO is not supported here.
Anyway, your issue seems you do not defined: `HAL_ETH_LEGACY_MODULE_ENABLED`
See #61
